// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NFywmN8expwievB49ovjRow-EmgOw80',
    appId: '1:680338894328:web:8cc930f69bc81cbeeb7a0d',
    messagingSenderId: '680338894328',
    projectId: 'highschoolvn-dev',
    authDomain: 'highschoolvn-dev.firebaseapp.com',
    databaseURL: 'https://highschoolvn-dev-default-rtdb.firebaseio.com',
    storageBucket: 'highschoolvn-dev.appspot.com',
    measurementId: 'G-FSL34XPVYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcS4RXv53DerwDG27CCVRxG8jklGj9VsQ',
    appId: '1:680338894328:android:d59c2d275374fe44eb7a0d',
    messagingSenderId: '680338894328',
    projectId: 'highschoolvn-dev',
    databaseURL: 'https://highschoolvn-dev-default-rtdb.firebaseio.com',
    storageBucket: 'highschoolvn-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSOuRY4wjSO6eaTfiydIkSlkOMCyx7Eg',
    appId: '1:680338894328:ios:7278881995dd93c8eb7a0d',
    messagingSenderId: '680338894328',
    projectId: 'highschoolvn-dev',
    databaseURL: 'https://highschoolvn-dev-default-rtdb.firebaseio.com',
    storageBucket: 'highschoolvn-dev.appspot.com',
    iosBundleId: 'com.example.uniAdPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSOuRY4wjSO6eaTfiydIkSlkOMCyx7Eg',
    appId: '1:680338894328:ios:7278881995dd93c8eb7a0d',
    messagingSenderId: '680338894328',
    projectId: 'highschoolvn-dev',
    databaseURL: 'https://highschoolvn-dev-default-rtdb.firebaseio.com',
    storageBucket: 'highschoolvn-dev.appspot.com',
    iosBundleId: 'com.example.uniAdPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7NFywmN8expwievB49ovjRow-EmgOw80',
    appId: '1:680338894328:web:d5ffdcc504ddab88eb7a0d',
    messagingSenderId: '680338894328',
    projectId: 'highschoolvn-dev',
    authDomain: 'highschoolvn-dev.firebaseapp.com',
    databaseURL: 'https://highschoolvn-dev-default-rtdb.firebaseio.com',
    storageBucket: 'highschoolvn-dev.appspot.com',
    measurementId: 'G-LC1EW4JNV6',
  );
}
